export default dateRangePickerActionTypes;
function dateRangePickerActionTypes (prefix = 'DEFAULT') {
	return {
		DATE_PICKER_TOGGLE_DROPDOWN: `${prefix}_DATE_PICKER_TOGGLE_DROPDOWN`,
		DATE_PICKER_OPEN_DROPDOWN: `${prefix}_DATE_PICKER_OPEN_DROPDOWN`,
		DATE_PICKER_CLOSE_DROPDOWN: `${prefix}_DATE_PICKER_CLOSE_DROPDOWN`,
		DATE_PICKER_SHIFT_CURRENT_MONTH: `${prefix}_DATE_PICKER_SHIFT_CURRENT_MONTH`,
		DATE_PICKER_SELECT_DATE: `${prefix}_DATE_PICKER_SELECT_DATE`,
	};
}
