export default dateRangePickerActionTypes;
function dateRangePickerActionTypes (prefix = 'DEFAULT') {
	return {
		DATE_FILTER_TOGGLE_DROPDOWN: `${prefix}_DATE_FILTER_TOGGLE_DROPDOWN`,
		DATE_FILTER_OPEN_DROPDOWN: `${prefix}_DATE_FILTER_OPEN_DROPDOWN`,
		DATE_FILTER_CLOSE_DROPDOWN: `${prefix}_DATE_FILTER_CLOSE_DROPDOWN`,
		DATE_FILTER_SHIFT_CURRENT_MONTH: `${prefix}_DATE_FILTER_SHIFT_CURRENT_MONTH`,
		DATE_FILTER_SELECT_DATE: `${prefix}_DATE_FILTER_SELECT_DATE`,
	};
}
